### ISSUE TITLE
Issues with types

### ISSUE THREAD

**Issue by mthenw** [chadlavi/react-highlighter-ts#3]
Hey, thanks for a great project! I want to report two issues with TS types.

1. I need to import the component from `react-highlighter-ts/dist/lib` otherwise I get the following error
![image](https://user-images.githubusercontent.com/455261/107892758-8161a580-6f27-11eb-867d-9877c826aac6.png)

2. `css` property is required
![image](https://user-images.githubusercontent.com/455261/107892785-a229fb00-6f27-11eb-9945-6bb0ec08eb31.png)

**Comment by chadlavi** [comment]
@mthenw huh thanks for that! yes this first one is a quick change to add a `types` key to the package.json so your app knows where to look. 

As for that second one, that's probably an issue with the way I'm extending `React.HTMLAttributes<HTMLSpanElement>`. You don't happen to have a code snippet to replicate this with do you?

(and sorry for the rather long delay in replying)

**Comment by chadlavi** [comment]
This should be resolved in `2.0.1`, please let me know if it isn't
