### ISSUE TITLE
search doesn't get type from state

### ISSUE THREAD

**Issue by MichalFrontEnd** [chadlavi/react-highlighter-ts#5]
I want my search phrase to come from a state hook, but even though it is defined as a string on the interface (and can be inferred as well) the code won't run unless I hard code a string there.
Disclaimer: I'm very new to TS.

**Comment by chadlavi** [comment]
Not sure what you mean here Michal, but here's an example of getting the `Highlight` component's search string from a state hook: https://codesandbox.io/s/vigilant-dawn-vj5c9?file=/src/App.tsx
